#' Dummy function to satisfy R CMD check that packages in Imports are used
#'
#' @keywords internal
#' @name dummy_imports
dummy_imports <- function() {
  affy::ReadAffy
  AnnotationDbi::mapIds
  Biobase::exprs
  biomaRt::useMart
  caret::createFolds
  circlize::chordDiagram
  clusterProfiler::enrichGO
  clusterProfiler::GSEA
  data.table::fread
  DESeq2::DESeqDataSetFromMatrix
  dplyr::mutate
  DT::datatable
  dynamicTreeCut::cutreeDynamic
  edgeR::DGEList
  enrichplot::dotplot
  enrichplot::gseaplot2
  GEOquery::getGEO
  ggplot2::ggplot
  ggpubr::ggboxplot
  ggraph::ggraph
  ggrepel::geom_text_repel
  glmnet::cv.glmnet
  gridExtra::grid.arrange
  igraph::graph_from_data_frame
  limma::lmFit
  msigdbr::msigdbr
  oligo::read.celfiles
  org.Hs.eg.db::org.Hs.eg.db
  parallel::detectCores
  pheatmap::pheatmap
  pROC::roc
  randomForest::randomForest
  R.utils::gunzip
  RColorBrewer::brewer.pal
  reshape2::melt
  rms::lrm
  scales::comma
  shiny::shinyApp
  shinydashboard::dashboardPage
  shinyjs::useShinyjs
  STRINGdb::STRINGdb
  sva::ComBat
  tibble::tibble
  tidyr::gather
  tidygraph::as_tbl_graph
  UpSetR::upset
  VennDiagram::venn.diagram
  WGCNA::blockwiseModules
  xgboost::xgb.train
  cli::cli_bullets
  glue::glue
  lifecycle::deprecate_warn
  Matrix::Matrix
  methods::slot
  methods::slotNames
  pillar::new_pillar
  Rcpp::evalCpp
  rlang::is_character
  vctrs::vec_size
  withr::with_options
  withr::local_seed
  withr::with_seed
  invisible(NULL)
}
